# Generated by Django 5.1.14 on 2025-11-10 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('student_id', models.CharField(blank=True, max_length=30)),
                ('default_pickup_location', models.CharField(blank=True, help_text='e.g. Student Union, Dorm Front Desk, CS Building Lobby', max_length=100)),
                ('delivery_notes', models.CharField(blank=True, help_text='Short instructions for pickup or delivery drop-off.', max_length=255)),
                ('promo_opt_in', models.BooleanField(default=True, help_text='Receive Rowdy Mart deals and promos.')),
                ('order_updates_opt_in', models.BooleanField(default=True, help_text='Receive notifications about your orders.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
